config/routes.rb
Tvtime::Application.routes.draw do
  resources :families

   root :to => 'Families#index'

end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :hours_spent_watching, :name, :state, :televisions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  # GET /families
  # GET /families.json
  def index
    @families = Family.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @families }
    end
  end

  # GET /families/1
  # GET /families/1.json
  def show
    @family = Family.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @family }
    end
  end

  # GET /families/new
  # GET /families/new.json
  def new
    @family = Family.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @family }
    end
  end

  # GET /families/1/edit
  def edit
    @family = Family.find(params[:id])
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(params[:family])

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render json: @family, status: :created, location: @family }
      else
        format.html { render action: "new" }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /families/1
  # PUT /families/1.json
  def update
    @family = Family.find(params[:id])

    respond_to do |format|
      if @family.update_attributes(params[:family])
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family = Family.find(params[:id])
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label "Number of #{:televisions}" %><br />
    <%= f.number_field :televisions %>
  </div>
  <div class="field">
    <%= f.label "#{:hours_spent_watching} per day" %><br />
    <%= f.number_field :hours_spent_watching %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing family</h1>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<h1>Listing families</h1>

<table>
  <tr>
    <th>Name</th>
    <th>State</th>
    <th>Televisions</th>
    <th>Hours spent watching</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @families.each do |family| %>
  <tr>
    <td><%= family.name %></td>
    <td><%= family.state %></td>
    <td><%= family.televisions %></td>
    <td><%= family.hours_spent_watching %></td>
    <td><%= link_to 'Show', family %></td>
    <td><%= link_to 'Edit', edit_family_path(family) %></td>
    <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @family.name %>
</p>

<p>
  <b>State:</b>
  <%= @family.state %>
</p>

<p>
  <b>Televisions:</b>
  <%= @family.televisions %>
</p>

<p>
  <b>Hours spent watching:</b>
  <%= @family.hours_spent_watching %>
</p>


<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tvtime</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>